### ISSUE TITLE
Unable to run generate_train_data script

### ISSUE THREAD

**Issue by asail77** [datitran/face2face-demo#1]
Hi @datitran,
Just tried to run the generate_train_data script and I get the below error.  I'm messing around with the environment.yml to see if there is some dependency in there that is not correct.  

I have Anaconda3-4.2.0-MacOSX-x86_64.pkg installed from https://repo.continuum.io/archive/ (Anaconda / Python 3.5).  

The error:

python generate_train_data.py --file vidfile2.mov --num 400 --landmark landmark.dat
Traceback (most recent call last):
  File "generate_train_data.py", line 3, in <module>
    import dlib
ImportError: dlopen(/Applications/anaconda/envs/face2face-demo/lib/python3.5/site-packages/dlib.so, 2): Symbol not found: __ZN5boost6python7objects15function_objectERKNS1_11py_functionERKNSt3__14pairIPKNS0_6detail7keywordESA_EE
  Referenced from: /Applications/anaconda/envs/face2face-demo/lib/python3.5/site-packages/dlib.so
  Expected in: /Applications/anaconda/envs/face2face-demo/lib/libboost_python3.dylib
 in /Applications/anaconda/envs/face2face-demo/lib/python3.5/site-packages/dlib.so

Any help would be appreciated! 

-Ali

**Comment by datitran** [comment]
There seems to be a problem with dlib and conda. Have you looked at this already: https://github.com/conda-forge/dlib-feedstock/issues/5.

**Comment by asail77** [comment]
Thanks for getting back to me!  I did see this post.  So I tired changing Boost to 1.61 (from 1.59) in the environment.yml file and get this error:
UnsatisfiableError: The following specifications were found to be in conflict:
  - bzip2 1.0.6 3
  - dlib 19.4 py35_0 -> boost 1.59.*
I'm curious how you didn't run into this problem since your environment.yml file calls out each version and dependency that is needed.

**Comment by asail77** [comment]
Ok.  So I ran the following commands to make it work:

conda config --add channels conda-forge
conda install dlib

Thanks!
