### ISSUE TITLE
Error: Key generator/encoder_8/conv/filter not found in checkpoint

### ISSUE THREAD

**Issue by lionawurscht** [datitran/face2face-demo#13]
Hey, I just finished training for ~2 days and now tried to continue with your instructions.
Since that step isn't described: I guessed I had to copy the face2face-model folder over to the root of your projects folder and then ran:
`python reduce_model.py --model-input face2face-model --model-output face2face-reduced-model`
Unfortunately that led to a big error message:

> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
>     return fn(*args)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
>     status, run_metadata)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: Key generator/encoder_8/conv/filter not found in checkpoint
> 	 [[Node: save/RestoreV2_43 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_43/tensor_names, save/RestoreV2_43/shape_and_slices)]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "reduce_model.py", line 215, in <module>
>     saver.restore(sess, checkpoint)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
>     run_metadata_ptr)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
>     options, run_metadata)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Key generator/encoder_8/conv/filter not found in checkpoint
> 	 [[Node: save/RestoreV2_43 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_43/tensor_names, save/RestoreV2_43/shape_and_slices)]]
> 
> Caused by op 'save/RestoreV2_43', defined at:
>   File "reduce_model.py", line 214, in <module>
>     saver = tf.train.Saver()
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
>     self.build()
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
>     build_save=build_save, build_restore=build_restore)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
>     restore_sequentially, reshape)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
>     tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
>     [spec.tensor.dtype])[0])
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
>     shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
>     op_def=op_def)
>   File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> NotFoundError (see above for traceback): Key generator/encoder_8/conv/filter not found in checkpoint
> 	 [[Node: save/RestoreV2_43 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_43/tensor_names, save/RestoreV2_43/shape_and_slices)]]

I have to admit that I never worked with tensorflow and used the version 1.4.1. I tried downgrading to 1.2.1 but that led to another error. Should I retrain with the older version of tensorflow or am I missing something else?

**Comment by lionawurscht** [comment]
Thanks, that solved it :)

**Comment by neelkadia** [comment]
@lionawurscht @qz517 Should I retrain the model after downgrading to older pix2pix?
