### ISSUE TITLE
NotFoundError

### ISSUE THREAD

**Issue by TangChangcheng** [datitran/face2face-demo#14]
NotFoundError (see above for traceback): Key generator/decoder_5/deconv/filter not found in checkpoint.

I found that there are many difference about name scope and network between reduce_mode.py and pix2pix.py, so I am wondering how do you guys work it out...

**Comment by mansonami** [comment]
I found the same problems, it seems that the tf.variables are not same with pix2pix-train.
-------------------------------------------------------------------------------------------------

NotFoundError (see above for traceback): Key generator/decoder_6/deconv/filter not found in checkpoint
         [[Node: save/RestoreV2_15 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv
_save/Const_0, save/RestoreV2_15/tensor_names, save/RestoreV2_15/shape_and_slices)]]
         [[Node: save/RestoreV2_14/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu
:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_180_save/RestoreV
2_14", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by mansonami** [comment]
load_images/input_producer/Const (<tf.Tensor 'load_images/input_producer/Const:0' shape=(207,) dtype=string>,)
load_images/input_producer/Size (<tf.Tensor 'load_images/input_producer/Size:0' shape=() dtype=int32>,)
load_images/input_producer/Greater/y (<tf.Tensor 'load_images/input_producer/Greater/y:0' shape=() dtype=int32>,)
load_images/input_producer/Greater (<tf.Tensor 'load_images/input_producer/Greater:0' shape=() dtype=bool>,)
load_images/input_producer/Assert/Const (<tf.Tensor 'load_images/input_producer/Assert/Const:0' shape=() dtype=string>,)
load_images/input_producer/Assert/Assert/data_0 (<tf.Tensor 'load_images/input_producer/Assert/Assert/data_0:0' shape=() dtype=string>,)
load_images/input_producer/Assert/Assert ()
load_images/input_producer/Identity (<tf.Tensor 'load_images/input_producer/Identity:0' shape=(207,) dtype=string>,)
load_images/input_producer/RandomShuffle (<tf.Tensor 'load_images/input_producer/RandomShuffle:0' shape=(207,) dtype=string>,)
load_images/input_producer (<tf.Tensor 'load_images/input_producer:0' shape=() dtype=resource>,)
load_images/input_producer/input_producer_EnqueueMany ()
load_images/input_producer/input_producer_Close ()
load_images/input_producer/input_producer_Close_1 ()
load_images/input_producer/input_producer_Size (<tf.Tensor 'load_images/input_producer/input_producer_Size:0' shape=() dtype=int32>,)
load_images/input_producer/ToFloat (<tf.Tensor 'load_images/input_producer/ToFloat:0' shape=() dtype=float32>,)
load_images/input_producer/mul/y (<tf.Tensor 'load_images/input_producer/mul/y:0' shape=() dtype=float32>,)
load_images/input_producer/mul (<tf.Tensor 'load_images/input_producer/mul:0' shape=() dtype=float32>,)
load_images/input_producer/fraction_of_32_full/tags (<tf.Tensor 'load_images/input_producer/fraction_of_32_full/tags:0' shape=() dtype=string>,)
load_images/input_producer/fraction_of_32_full (<tf.Tensor 'load_images/input_producer/fraction_of_32_full:0' shape=() dtype=string>,)
load_images/WholeFileReaderV2 (<tf.Tensor 'load_images/WholeFileReaderV2:0' shape=() dtype=resource>,)
load_images/ReaderReadV2 (<tf.Tensor 'load_images/ReaderReadV2:0' shape=() dtype=string>, <tf.Tensor 'load_images/ReaderReadV2:1' shape=() dtype=string>)
load_images/DecodeJpeg (<tf.Tensor 'load_images/DecodeJpeg:0' shape=(?, ?, ?) dtype=uint8>,)
load_images/convert_image/Cast (<tf.Tensor 'load_images/convert_image/Cast:0' shape=(?, ?, ?) dtype=float32>,)
load_images/convert_image/y (<tf.Tensor 'load_images/convert_image/y:0' shape=() dtype=float32>,)
load_images/convert_image (<tf.Tensor 'load_images/convert_image:0' shape=(?, ?, ?) dtype=float32>,)
load_images/Shape (<tf.Tensor 'load_images/Shape:0' shape=(3,) dtype=int32>,)
load_images/strided_slice/stack (<tf.Tensor 'load_images/strided_slice/stack:0' shape=(1,) dtype=int32>,)
load_images/strided_slice/stack_1 (<tf.Tensor 'load_images/strided_slice/stack_1:0' shape=(1,) dtype=int32>,)
load_images/strided_slice/stack_2 (<tf.Tensor 'load_images/strided_slice/stack_2:0' shape=(1,) dtype=int32>,)
load_images/strided_slice (<tf.Tensor 'load_images/strided_slice:0' shape=() dtype=int32>,)
load_images/assert_equal/y (<tf.Tensor 'load_images/assert_equal/y:0' shape=() dtype=int32>,)
load_images/assert_equal/Equal (<tf.Tensor 'load_images/assert_equal/Equal:0' shape=() dtype=bool>,)
load_images/assert_equal/Const (<tf.Tensor 'load_images/assert_equal/Const:0' shape=(0,) dtype=int32>,)
load_images/assert_equal/All (<tf.Tensor 'load_images/assert_equal/All:0' shape=() dtype=bool>,)
load_images/assert_equal/Assert/Const (<tf.Tensor 'load_images/assert_equal/Assert/Const:0' shape=() dtype=string>,)
load_images/assert_equal/Assert/Const_1 (<tf.Tensor 'load_images/assert_equal/Assert/Const_1:0' shape=() dtype=string>,)
load_images/assert_equal/Assert/Const_2 (<tf.Tensor 'load_images/assert_equal/Assert/Const_2:0' shape=() dtype=string>,)
load_images/assert_equal/Assert/Const_3 (<tf.Tensor 'load_images/assert_equal/Assert/Const_3:0' shape=() dtype=string>,)
load_images/assert_equal/Assert/Assert/data_0 (<tf.Tensor 'load_images/assert_equal/Assert/Assert/data_0:0' shape=() dtype=string>,)
load_images/assert_equal/Assert/Assert/data_1 (<tf.Tensor 'load_images/assert_equal/Assert/Assert/data_1:0' shape=() dtype=string>,)
load_images/assert_equal/Assert/Assert/data_2 (<tf.Tensor 'load_images/assert_equal/Assert/Assert/data_2:0' shape=() dtype=string>,)
load_images/assert_equal/Assert/Assert/data_4 (<tf.Tensor 'load_images/assert_equal/Assert/Assert/data_4:0' shape=() dtype=string>,)
load_images/assert_equal/Assert/Assert ()
load_images/Identity (<tf.Tensor 'load_images/Identity:0' shape=(?, ?, 3) dtype=float32>,)
load_images/Shape_1 (<tf.Tensor 'load_images/Shape_1:0' shape=(3,) dtype=int32>,)
load_images/strided_slice_1/stack (<tf.Tensor 'load_images/strided_slice_1/stack:0' shape=(1,) dtype=int32>,)
load_images/strided_slice_1/stack_1 (<tf.Tensor 'load_images/strided_slice_1/stack_1:0' shape=(1,) dtype=int32>,)
load_images/strided_slice_1/stack_2 (<tf.Tensor 'load_images/strided_slice_1/stack_2:0' shape=(1,) dtype=int32>,)
load_images/strided_slice_1 (<tf.Tensor 'load_images/strided_slice_1:0' shape=() dtype=int32>,)
load_images/floordiv/y (<tf.Tensor 'load_images/floordiv/y:0' shape=() dtype=int32>,)
load_images/floordiv (<tf.Tensor 'load_images/floordiv:0' shape=() dtype=int32>,)
load_images/strided_slice_2/stack (<tf.Tensor 'load_images/strided_slice_2/stack:0' shape=(3,) dtype=int32>,)
load_images/strided_slice_2/stack_1/0 (<tf.Tensor 'load_images/strided_slice_2/stack_1/0:0' shape=() dtype=int32>,)
load_images/strided_slice_2/stack_1/2 (<tf.Tensor 'load_images/strided_slice_2/stack_1/2:0' shape=() dtype=int32>,)
load_images/strided_slice_2/stack_1 (<tf.Tensor 'load_images/strided_slice_2/stack_1:0' shape=(3,) dtype=int32>,)
load_images/strided_slice_2/stack_2 (<tf.Tensor 'load_images/strided_slice_2/stack_2:0' shape=(3,) dtype=int32>,)
load_images/strided_slice_2 (<tf.Tensor 'load_images/strided_slice_2:0' shape=(?, ?, 3) dtype=float32>,)
load_images/preprocess/mul/y (<tf.Tensor 'load_images/preprocess/mul/y:0' shape=() dtype=float32>,)
load_images/preprocess/mul (<tf.Tensor 'load_images/preprocess/mul:0' shape=(?, ?, 3) dtype=float32>,)
load_images/preprocess/sub/y (<tf.Tensor 'load_images/preprocess/sub/y:0' shape=() dtype=float32>,)
load_images/preprocess/sub (<tf.Tensor 'load_images/preprocess/sub:0' shape=(?, ?, 3) dtype=float32>,)
load_images/floordiv_1/y (<tf.Tensor 'load_images/floordiv_1/y:0' shape=() dtype=int32>,)
load_images/floordiv_1 (<tf.Tensor 'load_images/floordiv_1:0' shape=() dtype=int32>,)
load_images/strided_slice_3/stack/0 (<tf.Tensor 'load_images/strided_slice_3/stack/0:0' shape=() dtype=int32>,)
load_images/strided_slice_3/stack/2 (<tf.Tensor 'load_images/strided_slice_3/stack/2:0' shape=() dtype=int32>,)
load_images/strided_slice_3/stack (<tf.Tensor 'load_images/strided_slice_3/stack:0' shape=(3,) dtype=int32>,)
load_images/strided_slice_3/stack_1 (<tf.Tensor 'load_images/strided_slice_3/stack_1:0' shape=(3,) dtype=int32>,)
load_images/strided_slice_3/stack_2 (<tf.Tensor 'load_images/strided_slice_3/stack_2:0' shape=(3,) dtype=int32>,)
load_images/strided_slice_3 (<tf.Tensor 'load_images/strided_slice_3:0' shape=(?, ?, 3) dtype=float32>,)
load_images/preprocess_1/mul/y (<tf.Tensor 'load_images/preprocess_1/mul/y:0' shape=() dtype=float32>,)
load_images/preprocess_1/mul (<tf.Tensor 'load_images/preprocess_1/mul:0' shape=(?, ?, 3) dtype=float32>,)
load_images/preprocess_1/sub/y (<tf.Tensor 'load_images/preprocess_1/sub/y:0' shape=() dtype=float32>,)
load_images/preprocess_1/sub (<tf.Tensor 'load_images/preprocess_1/sub:0' shape=(?, ?, 3) dtype=float32>,)
input_images/Shape (<tf.Tensor 'input_images/Shape:0' shape=(3,) dtype=int32>,)
input_images/assert_positive/Const (<tf.Tensor 'input_images/assert_positive/Const:0' shape=() dtype=int32>,)
input_images/assert_positive/assert_less/Less (<tf.Tensor 'input_images/assert_positive/assert_less/Less:0' shape=(3,) dtype=bool>,)
input_images/assert_positive/assert_less/Const (<tf.Tensor 'input_images/assert_positive/assert_less/Const:0' shape=(1,) dtype=int32>,)
input_images/assert_positive/assert_less/All (<tf.Tensor 'input_images/assert_positive/assert_less/All:0' shape=() dtype=bool>,)
input_images/assert_positive/assert_less/Assert/Const (<tf.Tensor 'input_images/assert_positive/assert_less/Assert/Const:0' shape=() dtype=string>,)
input_images/assert_positive/assert_less/Assert/Assert/data_0 (<tf.Tensor 'input_images/assert_positive/assert_less/Assert/Assert/data_0:0' shape=() dtype=string>,)
input_images/assert_positive/assert_less/Assert/Assert ()
input_images/control_dependency (<tf.Tensor 'input_images/control_dependency:0' shape=(?, ?, 3) dtype=float32>,)
input_images/random_uniform/shape (<tf.Tensor 'input_images/random_uniform/shape:0' shape=(0,) dtype=int32>,)
input_images/random_uniform/min (<tf.Tensor 'input_images/random_uniform/min:0' shape=() dtype=float32>,)
input_images/random_uniform/max (<tf.Tensor 'input_images/random_uniform/max:0' shape=() dtype=float32>,)
input_images/random_uniform/RandomUniform (<tf.Tensor 'input_images/random_uniform/RandomUniform:0' shape=() dtype=float32>,)
input_images/random_uniform/sub (<tf.Tensor 'input_images/random_uniform/sub:0' shape=() dtype=float32>,)
input_images/random_uniform/mul (<tf.Tensor 'input_images/random_uniform/mul:0' shape=() dtype=float32>,)
input_images/random_uniform (<tf.Tensor 'input_images/random_uniform:0' shape=() dtype=float32>,)
input_images/Less/y (<tf.Tensor 'input_images/Less/y:0' shape=() dtype=float32>,)
input_images/Less (<tf.Tensor 'input_images/Less:0' shape=() dtype=bool>,)
input_images/cond/Switch (<tf.Tensor 'input_images/cond/Switch:0' shape=() dtype=bool>, <tf.Tensor 'input_images/cond/Switch:1' shape=() dtype=bool>)
input_images/cond/switch_t (<tf.Tensor 'input_images/cond/switch_t:0' shape=() dtype=bool>,)

**Comment by TangChangcheng** [comment]
I found the solution that downloads previous pix2pix.py 2017.07 version instead of the latest.

**Comment by mansonami** [comment]
Thanks very much.

I will try.






At 2018-02-13 11:53:52, "TangChangcheng" <notifications@github.com> wrote:


I found the solution that downloads previous pix2pix.py 2017.07 version instead of the latest.
