### ISSUE TITLE
Extremely blurry result with distorted colours

### ISSUE THREAD

**Issue by wanshun123** [datitran/face2face-demo#31]
I've tested on the Merkel video as in the readme, first testing on a model trained to 200 epochs and also on a model trained to 1000 epochs. Both models produce similarly poor results:

![frame_screenshot_28 12 2018](https://user-images.githubusercontent.com/11178170/50532573-2bb6bd00-0b56-11e9-87be-4e7ed40e4317.png)

My input video is a very high quality .mp4 video, though as can be seen the subject was definitely too close to the camera compared to the Merkel video. Any advice on improving results? I am wondering if there's any possibility of reproducing the extremely high quality example from the original face2face researchers (https://www.youtube.com/watch?v=ohmajJTcpNk).

**Comment by Atin17** [comment]
Maybe you should sit at the same distance as the person in your dataset.

**Comment by wanshun123** [comment]
It is definitely necessary to sit at the exact same distance from the camera as the source being controlled, though I am still getting blurry results. I think to try to replicate face2face from https://www.youtube.com/watch?v=ohmajJTcpNk is outside the scope of this repo.

**Comment by Atin17** [comment]
I think the part for generating the face landmarks is quite different for both but still my results were above average.        
https://github.com/Atin17/Deep-Learning/blob/master/face2face/README.md
